/**
 * T066 breaking-change detector
 * (`specs/001-platform-foundation-shell/tasks.md` T066, FR-038, SC-008;
 * `docs/decisions/0004-validation-contract-integration.md`).
 *
 * Deliberately narrow, per this task's own instructions: a general
 * OpenAPI-semantics diff is exactly the kind of generic abstraction
 * `AGENTS.md` warns against building without demonstrated repeated need.
 * This compares two OpenAPI 3.0 documents and flags only the patterns that
 * can actually break an existing `@slotnova/contracts` consumer
 * (`openapi-fetch`/`openapi-msw` typed callers generated from `paths` /
 * `components.schemas`):
 *
 * - a previously-documented path removed
 * - a previously-documented operation (method on a path) removed
 * - a request/response schema's previously-required field removed, or
 *   removed from `required` entirely (same typed-caller-breaking failure
 *   mode as full removal: a field a caller could rely on being present
 *   stops being guaranteed)
 * - a previously-optional field becoming newly required (breaks any
 *   existing caller that omitted it)
 * - a field's `type` narrowing incompatibly (e.g. `string` -> `integer`;
 *   any change of `type` is treated as breaking -- this repo's generated
 *   clients are structurally typed from this exact value, so no change of
 *   `type` is guaranteed source-compatible)
 * - a previously-documented response status removed from a still-present
 *   operation, or a response's content schema `$ref` repointed at a
 *   different schema (added for the PR-15 review gap, T064-T067 follow-up:
 *   every endpoint's `problem+json` error responses are now documented via
 *   a shared `ProblemDetailsDto` `$ref` -- a typed caller (`openapi-fetch`'s
 *   discriminated-by-status response type) that narrowed on a documented
 *   error status disappearing, or on what schema that status's body
 *   satisfies, is exactly as broken as a removed success field)
 *
 * Explicitly NOT flagged (additive, per T066's spec): new paths, new
 * operations, new optional fields, new schemas, new response statuses on an
 * existing operation, a field moving from required to optional (loosening a
 * guarantee never breaks a caller that already tolerated its absence...
 * except it never could, since it was required -- the point is only that no
 * *existing* caller pattern breaks).
 *
 * No third-party OpenAPI-diff library is used -- `pnpm-lock.yaml` has none
 * in this repo's dependency tree (checked directly), and the scope above is
 * narrow and precisely specified, matching this repo's stated preference
 * for purpose-built code over a heavy generic dependency.
 *
 * Determinism (T066 "Constraints: deterministic ordering"): every source of
 * iteration order below is explicitly sorted before being walked or
 * reported -- `Object.keys()` order over a `JSON.parse()`-produced object is
 * insertion order per spec (stable for a *given* document), but the two
 * documents being compared are never guaranteed to share key order (e.g.
 * one is freshly regenerated, the other is `git show`'d from a past commit
 * generated by a different schema edit history), so relying on it directly
 * would be a real, not just theoretical, nondeterminism risk. Findings are
 * sorted by a stable composite key as the final step.
 */

export interface OpenApiOperation {
  operationId?: string;
  requestBody?: {
    required?: boolean;
    content?: Record<string, { schema?: OpenApiSchemaRef }>;
  };
  responses?: Record<
    string,
    { description?: string; content?: Record<string, { schema?: OpenApiSchemaRef }> }
  >;
}

export type HttpMethod = "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace";

export type OpenApiPathItem = Partial<Record<HttpMethod, OpenApiOperation>>;

export interface OpenApiSchemaRef {
  $ref?: string;
  type?: string;
  properties?: Record<string, OpenApiSchemaRef>;
  required?: string[];
  items?: OpenApiSchemaRef;
  nullable?: boolean;
}

export interface OpenApiDocument {
  openapi: string;
  info: { title: string; version: string };
  paths: Record<string, OpenApiPathItem>;
  components?: { schemas?: Record<string, OpenApiSchemaRef> };
}

const HTTP_METHODS: readonly HttpMethod[] = [
  "get",
  "put",
  "post",
  "delete",
  "options",
  "head",
  "patch",
  "trace",
];

export type BreakingChange =
  | { kind: "path-removed"; path: string }
  | { kind: "operation-removed"; path: string; method: HttpMethod }
  | { kind: "required-field-removed"; schema: string; field: string }
  | { kind: "field-newly-required"; schema: string; field: string }
  | { kind: "field-type-changed"; schema: string; field: string; from: string; to: string }
  | { kind: "response-removed"; path: string; method: HttpMethod; status: string }
  | {
      kind: "response-ref-changed";
      path: string;
      method: HttpMethod;
      status: string;
      from: string;
      to: string;
    };

/** Stable sort key so findings never flap in report ordering across runs. */
function sortKey(change: BreakingChange): string {
  switch (change.kind) {
    case "path-removed":
      return `1|${change.path}`;
    case "operation-removed":
      return `2|${change.path}|${change.method}`;
    case "required-field-removed":
      return `3|${change.schema}|${change.field}`;
    case "field-newly-required":
      return `4|${change.schema}|${change.field}`;
    case "field-type-changed":
      return `5|${change.schema}|${change.field}`;
    case "response-removed":
      return `6|${change.path}|${change.method}|${change.status}`;
    case "response-ref-changed":
      return `7|${change.path}|${change.method}|${change.status}`;
  }
}

function sortedKeys(record: Record<string, unknown> | undefined): string[] {
  return Object.keys(record ?? {}).sort();
}

/**
 * Diffs one still-present operation's `responses` map: a previously-
 * documented status disappearing, or its content schema's `$ref` changing.
 * Only the first `content` media type's `schema.$ref` is compared (every
 * response this repo documents is single-media-type -- `application/json`
 * for success, `application/problem+json` for errors -- confirmed by reading
 * every controller's decorators; a response with no `content`/`$ref` at all,
 * e.g. a bare `204`, has nothing to compare and is skipped).
 */
function diffResponses(
  path: string,
  method: HttpMethod,
  oldOperation: OpenApiOperation,
  newOperation: OpenApiOperation,
): BreakingChange[] {
  const findings: BreakingChange[] = [];
  const oldResponses = oldOperation.responses ?? {};
  const newResponses = newOperation.responses ?? {};

  for (const status of sortedKeys(oldResponses)) {
    const oldResponse = oldResponses[status];
    const newResponse = newResponses[status];
    if (!oldResponse) continue;

    if (!newResponse) {
      findings.push({ kind: "response-removed", path, method, status });
      continue;
    }

    const oldRef = firstContentRef(oldResponse.content);
    const newRef = firstContentRef(newResponse.content);
    if (oldRef !== undefined && newRef !== undefined && oldRef !== newRef) {
      findings.push({
        kind: "response-ref-changed",
        path,
        method,
        status,
        from: oldRef,
        to: newRef,
      });
    }
  }

  return findings;
}

function firstContentRef(
  content: Record<string, { schema?: OpenApiSchemaRef }> | undefined,
): string | undefined {
  if (!content) return undefined;
  for (const mediaType of Object.keys(content).sort()) {
    const ref = content[mediaType]?.schema?.$ref;
    if (ref !== undefined) return ref;
  }
  return undefined;
}

function diffPathsAndOperations(
  oldDoc: OpenApiDocument,
  newDoc: OpenApiDocument,
): BreakingChange[] {
  const findings: BreakingChange[] = [];

  for (const path of sortedKeys(oldDoc.paths)) {
    const oldPathItem = oldDoc.paths[path];
    const newPathItem = newDoc.paths[path];
    if (!oldPathItem) continue;

    if (!newPathItem) {
      findings.push({ kind: "path-removed", path });
      continue;
    }

    for (const method of HTTP_METHODS) {
      const oldOperation = oldPathItem[method];
      const newOperation = newPathItem[method];
      if (!oldOperation) continue;

      if (!newOperation) {
        findings.push({ kind: "operation-removed", path, method });
        continue;
      }

      // Only diff responses for an operation still present on both sides --
      // a removed operation is already reported once above (`operation-
      // removed`); re-reporting each of its responses too would be a
      // duplicate, less-specific finding for the same root cause.
      findings.push(...diffResponses(path, method, oldOperation, newOperation));
    }
  }

  return findings;
}

/** Diffs one schema's own `properties`/`required` (shallow -- see module doc for scope). */
function diffSchema(
  name: string,
  oldSchema: OpenApiSchemaRef,
  newSchema: OpenApiSchemaRef,
): BreakingChange[] {
  const findings: BreakingChange[] = [];
  const oldRequired = new Set(oldSchema.required ?? []);
  const newRequired = new Set(newSchema.required ?? []);
  const oldProperties = oldSchema.properties ?? {};
  const newProperties = newSchema.properties ?? {};

  for (const field of sortedKeys(oldProperties)) {
    const wasRequired = oldRequired.has(field);
    const stillPresent = field in newProperties;

    // A required field that disappears entirely is breaking regardless of
    // `required` bookkeeping. A required field that is merely demoted to
    // optional while remaining present is a *loosened* guarantee -- an
    // existing typed caller that always sent/read it keeps compiling and
    // working, so it is deliberately NOT flagged (see module doc).
    if (wasRequired && !stillPresent) {
      findings.push({ kind: "required-field-removed", schema: name, field });
      continue;
    }

    if (stillPresent) {
      const oldType = oldProperties[field]?.type;
      const newType = newProperties[field]?.type;
      if (oldType !== undefined && newType !== undefined && oldType !== newType) {
        findings.push({
          kind: "field-type-changed",
          schema: name,
          field,
          from: oldType,
          to: newType,
        });
      }
    }
  }

  for (const field of sortedKeys(newProperties)) {
    if (!oldRequired.has(field) && newRequired.has(field)) {
      findings.push({ kind: "field-newly-required", schema: name, field });
    }
  }

  return findings;
}

function diffSchemas(oldDoc: OpenApiDocument, newDoc: OpenApiDocument): BreakingChange[] {
  const findings: BreakingChange[] = [];
  const oldSchemas = oldDoc.components?.schemas ?? {};
  const newSchemas = newDoc.components?.schemas ?? {};

  for (const name of sortedKeys(oldSchemas)) {
    const oldSchema = oldSchemas[name];
    const newSchema = newSchemas[name];
    // A removed schema is only actually breaking if something still
    // references it; a bare unreferenced-schema removal has no narrow,
    // precisely-specified failure mode in this task's defined scope, so it
    // is deliberately left undetected here (see module doc: path/operation
    // removal already covers the caller-facing surface that matters).
    if (!oldSchema || !newSchema) continue;
    findings.push(...diffSchema(name, oldSchema, newSchema));
  }

  return findings;
}

/**
 * Compares an old (base) and new (current) OpenAPI 3.0 document and returns
 * every breaking change found, deterministically ordered. Pure function --
 * no filesystem/process access -- so it is directly unit-testable
 * (`__tests__/detect-breaking-changes.test.ts`) and reusable from both the
 * CLI entry point below and any future caller.
 */
export function detectBreakingChanges(
  oldDoc: OpenApiDocument,
  newDoc: OpenApiDocument,
): BreakingChange[] {
  const findings = [...diffPathsAndOperations(oldDoc, newDoc), ...diffSchemas(oldDoc, newDoc)];
  return findings.sort((a, b) => sortKey(a).localeCompare(sortKey(b)));
}

export function formatBreakingChange(change: BreakingChange): string {
  switch (change.kind) {
    case "path-removed":
      return `path removed: ${change.path}`;
    case "operation-removed":
      return `operation removed: ${change.method.toUpperCase()} ${change.path}`;
    case "required-field-removed":
      return `required field removed: ${change.schema}.${change.field}`;
    case "field-newly-required":
      return `field newly required (was optional): ${change.schema}.${change.field}`;
    case "field-type-changed":
      return `field type changed: ${change.schema}.${change.field} (${change.from} -> ${change.to})`;
    case "response-removed":
      return `response removed: ${change.status} ${change.method.toUpperCase()} ${change.path}`;
    case "response-ref-changed":
      return `response schema changed: ${change.status} ${change.method.toUpperCase()} ${change.path} (${change.from} -> ${change.to})`;
  }
}
